services:
  - type: web
    name: portfolio-api
    env: docker
    region: singapore
    plan: free
    rootDir: portfolio-api
    dockerfilePath: portfolio-api/Dockerfile
    healthCheckPath: /ping
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://pg-273672a8-ayushmansingh2512-3047.d.aivencloud.com:12413/defaultdb?sslmode=require
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
